apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-app
  namespace: logistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting-app
  template:
    metadata:
      labels:
        app: reporting-app
    spec:
      containers:
        - name: reporting-app
          image: logistics-reporting-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 32Mi
              cpu: 50m
            limits:
              memory: 64Mi
              cpu: 100m
